/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jesica
 */
public class Flores extends javax.swing.JFrame {

    /**
     * Creates new form Flores
     */
    public Flores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        salida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 450));
        setMinimumSize(new java.awt.Dimension(550, 450));
        setPreferredSize(new java.awt.Dimension(550, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Elephant", 2, 14)); // NOI18N
        jLabel1.setText("NOMBRE DE FLOR:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 176, 52);

        jComboBox1.setBackground(new java.awt.Color(255, 102, 153));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 102, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Rosa", "Clavel", "Jasmin", "Cala", "Margarita" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 170, 170, 21);

        salida.setBackground(new java.awt.Color(255, 204, 204));
        salida.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        salida.setForeground(new java.awt.Color(153, 0, 153));
        getContentPane().add(salida);
        salida.setBounds(210, 100, 151, 52);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFlores/floresImagen.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(550, 40));
        jLabel2.setMinimumSize(new java.awt.Dimension(550, 450));
        jLabel2.setPreferredSize(new java.awt.Dimension(550, 450));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String mensaje = "seleccione una flor";
        if (jComboBox1.getSelectedIndex()==0){
             salida.setText(mensaje);
             salida.setEnabled(false);
        }
        else
        {
        mensaje= jComboBox1.getSelectedItem().toString();
        salida.setText(mensaje);
        
        if (salida.isEnabled()==false)
            salida.setEnabled(true);
        }
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel salida;
    // End of variables declaration//GEN-END:variables
}
